# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: anastasia.floris@epfl.ch candice.habert@epfl.ch
author_name: Anastasia&Candice
github_org: candicehbt
package_name: pkapredict
project_name: pKaPredict
short_description: pKaPredict project
